// const Module = require("./oper")
// console.log(Module.add1(10,5))
// console.log(Module.sub1(10,5))
// console.log(Module.multi1(10,5))

const {add, sub, multi, div, rem} = require("./oper")
console.log(add(10,5))
console.log(sub(10,5))
console.log(multi(10,5))
console.log(div(10,5))
console.log(rem(10,5))
